name: Test

on: 
  push:
   branches:
    - main

jobs: 
  docker: 
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: start containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: create topics
        run: docker-compose exec -T kafka kafka-topics --create --topic test --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install
      - name: start mock mockServer
        run: nohup npx ezmockserver & > output.log & 
      - name: run tests
        run: npm run test
      - name: Stop Container
        if: always()
        run: docker-compose -f "docker-compose.yml" down
  example-test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install dependencies node app
        run: cd ./example/node-express-server && npm install
      - name: run node example
        run: nohup npm run startApp & > output.node.log
      - name: install dependencies node app
        run: cd ./tests/components && npm install        
      - name: start mock mockServer
        run: nohup npm run mock-server-up & > output.mock.log
      - name: run component tests
        run: npm run component-test     